name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS Elastic Beanstalk CLI (EB CLI)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create or Confirm ECR Repository
        run: |
          if ! aws ecr describe-repositories --repository-names my-web-app --region us-east-1; then
            echo "ECR repository 'my-web-app' not found. Creating repository..."
            aws ecr create-repository --repository-name my-web-app --region us-east-1
            sleep 10
          else
            echo "ECR repository 'my-web-app' exists."
          fi

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772070195.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t my-web-app .
          docker tag my-web-app:latest 724772070195.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest
          docker push 724772070195.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker my-web-app --region us-east-1

          # Get the status of the Elastic Beanstalk environment
          STATUS=$(eb status my-web-app-env | grep Status | awk '{print $2}')
          
          if [ "$STATUS" = "Ready" ]; then
            echo "Environment is Ready. Deploying..."
            eb deploy my-web-app-env
          else
            echo "Environment is broken. Deleting and recreating..."
            eb terminate my-web-app-env --force || true
            echo "Waiting for environment termination..."
            sleep 60
            eb create my-web-app-env --region us-east-1 --elb-t
