name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: my-web-app
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: us-east-1
          ENV_NAME: my-web-app-env
        run: |
          zip -r application.zip .
          aws elasticbeanstalk create-application-version --application-name my-web-app --version-label $GITHUB_SHA --source-bundle S3Bucket=$ECR_REGISTRY/$ECR_REPOSITORY/application.zip
          aws elasticbeanstalk update-environment --environment-name $ENV_NAME --version-label $GITHUB_SHA
