name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS Elastic Beanstalk CLI (EB CLI)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create ECR Repository (If Not Exists)
        run: |
          aws ecr describe-repositories --repository-names my-web-app --region us-east-1 || \
          aws ecr create-repository --repository-name my-web-app --region us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772070195.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t my-web-app .
          docker tag my-web-app:latest 724772070195.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest
          docker push 724772070195.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest

      - name: Verify Docker Image Locally
        run: |
          docker run --rm 724772070195.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest python -c "print('Docker image is running successfully')"

      - name: Set Up and Deploy to Elastic Beanstalk
        run: |
          eb init -p docker my-web-app --region us-east-1
          
          # Check if environment exists
          if eb list | grep -q "my-web-app-env"; then
            STATUS=$(eb status my-web-app-env | grep Status | awk '{print $2}')
            if [ "$STATUS" != "Ready" ]; then
              echo "Environment is in an invalid state. Deleting and recreating..."
              eb terminate my-web-app-env --force
              eb create my-web-app-env --region us-east-1 --elb-type application
            else
              echo "Environment exists and is ready."
              eb use my-web-app-env
            fi
          else
            echo "Environment does not exist, creating it."
            eb create my-web-app-env --region us-east-1 --elb-type application
          fi
          
          eb deploy my-web-app-env

      - name: Check Elastic Beanstalk Logs on Failure
        if: failure()
        run: |
          eb logs my-web-app-env || echo "Environment not in a valid state to fetch logs"
